{application,kv,
             [{registered,[]},
              {description,"kv"},
              {applications,[kernel,stdlib,elixir]},
              {mod,{'Elixir.KV',[]}},
              {vsn,"0.0.1"},
              {modules,['Elixir.KV','Elixir.KV.Bucket',
                        'Elixir.KV.Bucket.Supervisor','Elixir.KV.Registry',
                        'Elixir.KV.Supervisor']}]}.